from pose_editor.opensim.config import (
    ArmatureExportConfig, BoneConfig, JointConstraints, AxisConstraint, JointType
)


def create_cc5_human_config():
    config = ArmatureExportConfig()
    config.model_name = "cc5_nase_model"

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Hip",
        opensim_name="CC_Base_Hip",
        constraints=JointConstraints(
            joint_type=JointType.FREE),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Pelvis",
        opensim_name="CC_Base_Pelvis",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=6.414429,
                max_angle=6.414494,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.001149,
                max_angle=0.001185,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.007526,
                max_angle=-0.007494,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thigh",
        opensim_name="CC_Base_L_Thigh",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-106.067551,
                max_angle=81.510344,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-153.322584,
                max_angle=8.218172,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-186.503387,
                max_angle=12.506285,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Calf",
        opensim_name="CC_Base_L_Calf",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-118.867667,
                max_angle=0.118204,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.0,
                max_angle=0.0,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.0,
                max_angle=0.0,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Foot",
        opensim_name="CC_Base_L_Foot",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=36.505821,
                max_angle=110.117778,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.721398,
                max_angle=10.668078,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-55.735020,
                max_angle=5.554499,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ToeBase",
        opensim_name="CC_Base_L_ToeBase",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=11.464407,
                max_angle=49.284671,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=2.109285,
                max_angle=3.361792,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-0.621177,
                max_angle=1.023774,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thigh",
        opensim_name="CC_Base_R_Thigh",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-102.825875,
                max_angle=86.641482,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-13.490132,
                max_angle=164.252731,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-5.560288,
                max_angle=186.721939,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Calf",
        opensim_name="CC_Base_R_Calf",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-120.816457,
                max_angle=0.008968,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.0,
                max_angle=0.0,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.0,
                max_angle=0.0,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Foot",
        opensim_name="CC_Base_R_Foot",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=36.402169,
                max_angle=111.064388,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-14.347663,
                max_angle=27.870589,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-3.138367,
                max_angle=53.316177,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ToeBase",
        opensim_name="CC_Base_R_ToeBase",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=11.764457,
                max_angle=44.554294,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-3.332051,
                max_angle=-2.210923,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-0.623342,
                max_angle=0.653420,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Waist",
        opensim_name="CC_Base_Waist",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=19.225278,
                max_angle=45.387591,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-10.099833,
                max_angle=10.299013,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-7.572260,
                max_angle=6.362949,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Spine01",
        opensim_name="CC_Base_Spine01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-24.111381,
                max_angle=9.547667,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-16.225275,
                max_angle=18.231289,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-10.321427,
                max_angle=9.321599,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Spine02",
        opensim_name="CC_Base_Spine02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-12.792121,
                max_angle=9.657079,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.293244,
                max_angle=20.833004,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-2.705141,
                max_angle=2.169028,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_NeckTwist01",
        opensim_name="CC_Base_NeckTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.089835,
                max_angle=36.252759,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-10.115723,
                max_angle=8.664757,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-15.905818,
                max_angle=6.810440,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_NeckTwist02",
        opensim_name="CC_Base_NeckTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-11.946480,
                max_angle=10.421994,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-9.594653,
                max_angle=7.706813,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-9.457112,
                max_angle=8.791300,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Head",
        opensim_name="CC_Base_Head",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-41.868237,
                max_angle=4.219522,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-35,
                max_angle=35,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-15,
                max_angle=15,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Clavicle",
        opensim_name="CC_Base_L_Clavicle",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-31.536059,
                max_angle=20.165215,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.292865,
                max_angle=13.816843,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-107.416678,
                max_angle=-7.242663,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Upperarm",
        opensim_name="CC_Base_L_Upperarm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-14.856300,
                max_angle=111.419646,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-69.453434,
                max_angle=67.865914,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-114.045444,
                max_angle=4.263985,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Forearm",
        opensim_name="CC_Base_L_Forearm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=0.559156,
                max_angle=113.468492,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-75.258193,
                max_angle=55.856225,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.0,
                max_angle=0.0,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Hand",
        opensim_name="CC_Base_L_Hand",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-27.690345,
                max_angle=23.942198,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-25.663626,
                max_angle=11.496269,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-43.969790,
                max_angle=54.841925,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky1",
        opensim_name="CC_Base_L_Pinky1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-8.940148,
                max_angle=5.603056,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-8.139346,
                max_angle=8.541609,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-104.942804,
                max_angle=-4.149059,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky2",
        opensim_name="CC_Base_L_Pinky2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=2.112113,
                max_angle=3.131392,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.086302,
                max_angle=1.652846,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-83.547400,
                max_angle=-1.104479,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky3",
        opensim_name="CC_Base_L_Pinky3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.237564,
                max_angle=0.802701,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.312620,
                max_angle=0.377234,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-49.229398,
                max_angle=9.726841,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring1",
        opensim_name="CC_Base_L_Ring1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-1.405099,
                max_angle=5.609528,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-4.996723,
                max_angle=4.903310,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-92.762554,
                max_angle=-2.617411,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring2",
        opensim_name="CC_Base_L_Ring2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.325652,
                max_angle=1.480778,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.006497,
                max_angle=0.028297,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-114.043655,
                max_angle=-5.257178,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring3",
        opensim_name="CC_Base_L_Ring3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.846534,
                max_angle=2.370528,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-1.169863,
                max_angle=0.082655,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-49.497694,
                max_angle=5.105856,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid1",
        opensim_name="CC_Base_L_Mid1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.935568,
                max_angle=6.684497,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.252513,
                max_angle=2.261451,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-85.491436,
                max_angle=-4.200897,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid2",
        opensim_name="CC_Base_L_Mid2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.446485,
                max_angle=0.668841,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.026012,
                max_angle=0.161844,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-89.155053,
                max_angle=-0.348354,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid3",
        opensim_name="CC_Base_L_Mid3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=2.905389,
                max_angle=3.359008,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.038996,
                max_angle=0.499069,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-53.041152,
                max_angle=5.394840,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index1",
        opensim_name="CC_Base_L_Index1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.020406,
                max_angle=13.080151,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.757308,
                max_angle=11.133388,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-68.875928,
                max_angle=11.868658,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index2",
        opensim_name="CC_Base_L_Index2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.186831,
                max_angle=0.341535,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.137396,
                max_angle=-0.014232,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-71.435781,
                max_angle=-0.014700,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index3",
        opensim_name="CC_Base_L_Index3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.406275,
                max_angle=2.010651,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.210621,
                max_angle=1.011253,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-62.772048,
                max_angle=10.198092,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb1",
        opensim_name="CC_Base_L_Thumb1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=31.278998,
                max_angle=62.245447,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-15.324774,
                max_angle=41.544492,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-55.592563,
                max_angle=-10.620200,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb2",
        opensim_name="CC_Base_L_Thumb2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-30.562778,
                max_angle=-16.571950,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.073548,
                max_angle=1.170112,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=1.345488,
                max_angle=2.423290,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb3",
        opensim_name="CC_Base_L_Thumb3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.729012,
                max_angle=38.776835,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.845312,
                max_angle=1.108957,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=1.507646,
                max_angle=2.536636,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Clavicle",
        opensim_name="CC_Base_R_Clavicle",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.759806,
                max_angle=14.889780,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-13.774195,
                max_angle=-1.536163,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=5.976174,
                max_angle=102.700541,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Upperarm",
        opensim_name="CC_Base_R_Upperarm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-70.318867,
                max_angle=108.629193,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-62.138145,
                max_angle=129.077707,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-69.706506,
                max_angle=110.233106,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Forearm",
        opensim_name="CC_Base_R_Forearm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.259835,
                max_angle=117.794467,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-45.063338,
                max_angle=65.192277,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-65.244132,
                max_angle=123.277319,
            ),
        ),
        export_body=True
    ))


    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Hand",
        opensim_name="CC_Base_R_Hand",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-34.307518,
                max_angle=46.181238,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-62.121602,
                max_angle=26.182794,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-77.524109,
                max_angle=44.686226,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring1",
        opensim_name="CC_Base_R_Ring1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-0.234201,
                max_angle=8.025249,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-4.901628,
                max_angle=8.642693,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=2.613781,
                max_angle=92.766946,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring2",
        opensim_name="CC_Base_R_Ring2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.308559,
                max_angle=1.469489,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.025975,
                max_angle=-0.004951,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=5.261538,
                max_angle=121.951375,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring3",
        opensim_name="CC_Base_R_Ring3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.848793,
                max_angle=2.371376,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.119974,
                max_angle=1.167677,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-6.525223,
                max_angle=49.494761,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid1",
        opensim_name="CC_Base_R_Mid1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.412942,
                max_angle=11.189832,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-2.510980,
                max_angle=2.926147,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=4.198335,
                max_angle=79.406051,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid2",
        opensim_name="CC_Base_R_Mid2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.010383,
                max_angle=0.671984,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.216450,
                max_angle=0.007151,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.496869,
                max_angle=112.779523,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid3",
        opensim_name="CC_Base_R_Mid3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=2.973802,
                max_angle=3.370994,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.497162,
                max_angle=-0.031590,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-6.377009,
                max_angle=53.040374,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb1",
        opensim_name="CC_Base_R_Thumb1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=29.338354,
                max_angle=55.740170,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-49.322773,
                max_angle=15.340395,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=10.618596,
                max_angle=53.628084,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb2",
        opensim_name="CC_Base_R_Thumb2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-32.078895,
                max_angle=-17.600119,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-1.288115,
                max_angle=0.067858,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-2.432038,
                max_angle=-1.465050,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb3",
        opensim_name="CC_Base_R_Thumb3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.722800,
                max_angle=38.716446,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-1.110323,
                max_angle=0.923005,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-2.535775,
                max_angle=-1.483409,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index1",
        opensim_name="CC_Base_R_Index1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.024689,
                max_angle=13.280942,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-11.130931,
                max_angle=1.759482,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-11.852376,
                max_angle=59.336879,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index2",
        opensim_name="CC_Base_R_Index2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.171866,
                max_angle=0.341723,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.014718,
                max_angle=0.140386,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=0.018494,
                max_angle=79.249578,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index3",
        opensim_name="CC_Base_R_Index3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.359972,
                max_angle=2.037597,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-1.009636,
                max_angle=0.212728,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-10.105561,
                max_angle=62.769807,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky1",
        opensim_name="CC_Base_R_Pinky1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-7.811516,
                max_angle=5.614181,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-8.533954,
                max_angle=12.710864,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=4.148347,
                max_angle=109.743368,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky2",
        opensim_name="CC_Base_R_Pinky2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.352103,
                max_angle=3.106842,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-1.669014,
                max_angle=-0.086847,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.112503,
                max_angle=100.627285,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky3",
        opensim_name="CC_Base_R_Pinky3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.011448,
                max_angle=0.805677,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.376485,
                max_angle=0.312126,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-9.736617,
                max_angle=49.219501,
            ),
        ),
        export_body=True
    ))

    return config
