from pose_editor.opensim.config import (
    ArmatureExportConfig, BoneConfig, JointConstraints, AxisConstraint, JointType
)


def create_generated_config():
    config = ArmatureExportConfig()
    config.model_name = "cc5-base-male-calib-anim_generated"

    config.add_bone(BoneConfig(
        blender_name="CC_Base_BoneRoot", opensim_name="CC_Base_BoneRoot",
        constraints=JointConstraints(joint_type=JointType.FREE),
        export_body=True
    ))
    config.add_bone(BoneConfig(
        blender_name="CC_Base_Hip",
        opensim_name="CC_Base_Hip",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=86.966606,
                max_angle=163.239185,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-5.127829,
                max_angle=6.033795,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-123.543970,
                max_angle=0.332075,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Pelvis",
        opensim_name="CC_Base_Pelvis",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=6.414429,
                max_angle=6.414494,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.001149,
                max_angle=0.001185,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.007526,
                max_angle=-0.007494,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thigh",
        opensim_name="CC_Base_L_Thigh",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-106.067551,
                max_angle=81.510344,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-153.322584,
                max_angle=8.218172,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-186.503387,
                max_angle=12.506285,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Calf",
        opensim_name="CC_Base_L_Calf",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-118.867667,
                max_angle=0.118204,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-21.121506,
                max_angle=25.353900,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-12.222541,
                max_angle=19.037971,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Foot",
        opensim_name="CC_Base_L_Foot",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=36.505821,
                max_angle=110.117778,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.721398,
                max_angle=10.668078,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-55.735020,
                max_angle=5.554499,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ToeBaseShareBone",
        opensim_name="CC_Base_L_ToeBaseShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=11.976247,
                max_angle=11.976285,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=2.664399,
                max_angle=2.664417,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.051827,
                max_angle=-0.051794,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ToeBase",
        opensim_name="CC_Base_L_ToeBase",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=11.464407,
                max_angle=49.284671,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=2.109285,
                max_angle=3.361792,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-0.621177,
                max_angle=1.023774,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_PinkyToe1",
        opensim_name="CC_Base_L_PinkyToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-9.719514,
                max_angle=-9.719482,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=4.249255,
                max_angle=4.249275,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-3.503269,
                max_angle=-3.503234,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_RingToe1",
        opensim_name="CC_Base_L_RingToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-12.806763,
                max_angle=-12.806730,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=6.583750,
                max_angle=6.583762,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-1.222834,
                max_angle=-1.222800,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_MidToe1",
        opensim_name="CC_Base_L_MidToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-5.737340,
                max_angle=-5.737313,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=4.846952,
                max_angle=4.846972,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.141166,
                max_angle=0.141207,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_IndexToe1",
        opensim_name="CC_Base_L_IndexToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-3.618366,
                max_angle=-3.618331,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=5.426936,
                max_angle=5.426956,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.467440,
                max_angle=0.467480,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_BigToe1",
        opensim_name="CC_Base_L_BigToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=7.045079,
                max_angle=7.045111,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.172539,
                max_angle=0.172558,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-2.639471,
                max_angle=-2.639428,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_CalfTwist01",
        opensim_name="CC_Base_L_CalfTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000919,
                max_angle=-0.000793,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-27.089830,
                max_angle=26.134279,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.001462,
                max_angle=-0.000640,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_CalfTwist02",
        opensim_name="CC_Base_L_CalfTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000182,
                max_angle=-0.000142,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.588578,
                max_angle=5.553815,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000216,
                max_angle=-0.000130,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_KneeShareBone",
        opensim_name="CC_Base_L_KneeShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.670913,
                max_angle=61.140240,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-25.494665,
                max_angle=28.440513,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-3.687833,
                max_angle=3.561465,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ThighTwist01",
        opensim_name="CC_Base_L_ThighTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.002612,
                max_angle=0.002705,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-11.073496,
                max_angle=10.895794,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000352,
                max_angle=0.001389,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ThighTwist02",
        opensim_name="CC_Base_L_ThighTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000035,
                max_angle=0.000007,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-10.896192,
                max_angle=11.073123,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000023,
                max_angle=0.000005,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thigh",
        opensim_name="CC_Base_R_Thigh",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-102.825875,
                max_angle=86.641482,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-13.490132,
                max_angle=164.252731,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-5.560288,
                max_angle=186.721939,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Calf",
        opensim_name="CC_Base_R_Calf",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-120.816457,
                max_angle=0.008968,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-13.035656,
                max_angle=17.076988,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-7.390972,
                max_angle=10.122016,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_KneeShareBone",
        opensim_name="CC_Base_R_KneeShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.731349,
                max_angle=61.982847,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.403151,
                max_angle=13.125837,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-3.943139,
                max_angle=2.692234,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Foot",
        opensim_name="CC_Base_R_Foot",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=36.402169,
                max_angle=111.064388,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-14.347663,
                max_angle=27.870589,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-3.138367,
                max_angle=53.316177,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ToeBase",
        opensim_name="CC_Base_R_ToeBase",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=11.764457,
                max_angle=44.554294,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-3.332051,
                max_angle=-2.210923,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-0.623342,
                max_angle=0.653420,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_BigToe1",
        opensim_name="CC_Base_R_BigToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=7.043219,
                max_angle=7.043245,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.171812,
                max_angle=-0.171795,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=2.640771,
                max_angle=2.640803,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_PinkyToe1",
        opensim_name="CC_Base_R_PinkyToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-9.715712,
                max_angle=-9.715683,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-4.247849,
                max_angle=-4.247831,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=3.504533,
                max_angle=3.504559,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_RingToe1",
        opensim_name="CC_Base_R_RingToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-12.821471,
                max_angle=-12.821439,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-6.585193,
                max_angle=-6.585177,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=1.214564,
                max_angle=1.214598,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_IndexToe1",
        opensim_name="CC_Base_R_IndexToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-3.621114,
                max_angle=-3.621083,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-5.426986,
                max_angle=-5.426967,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.472639,
                max_angle=-0.472610,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_MidToe1",
        opensim_name="CC_Base_R_MidToe1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-5.740145,
                max_angle=-5.740114,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-4.846267,
                max_angle=-4.846250,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.142395,
                max_angle=-0.142359,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ToeBaseShareBone",
        opensim_name="CC_Base_R_ToeBaseShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=11.978489,
                max_angle=11.978529,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-2.664810,
                max_angle=-2.664795,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.052304,
                max_angle=0.052337,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_CalfTwist01",
        opensim_name="CC_Base_R_CalfTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000853,
                max_angle=-0.000790,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-16.431046,
                max_angle=15.082441,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000840,
                max_angle=0.001296,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_CalfTwist02",
        opensim_name="CC_Base_R_CalfTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000187,
                max_angle=-0.000144,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.773797,
                max_angle=21.923056,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000121,
                max_angle=0.000200,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ThighTwist01",
        opensim_name="CC_Base_R_ThighTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.002615,
                max_angle=0.002733,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-15.041605,
                max_angle=8.167725,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.001583,
                max_angle=-0.000488,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ThighTwist02",
        opensim_name="CC_Base_R_ThighTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000022,
                max_angle=0.000020,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-8.167328,
                max_angle=15.042006,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000001,
                max_angle=0.000021,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Waist",
        opensim_name="CC_Base_Waist",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=19.225278,
                max_angle=45.387591,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-10.099833,
                max_angle=10.299013,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-7.572260,
                max_angle=6.362949,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Spine01",
        opensim_name="CC_Base_Spine01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-24.111381,
                max_angle=9.547667,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-16.225275,
                max_angle=18.231289,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-10.321427,
                max_angle=9.321599,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Spine02",
        opensim_name="CC_Base_Spine02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-12.792121,
                max_angle=9.657079,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-18.293244,
                max_angle=20.833004,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-2.705141,
                max_angle=2.169028,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_NeckTwist01",
        opensim_name="CC_Base_NeckTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.089835,
                max_angle=36.252759,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-10.115723,
                max_angle=8.664757,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-15.905818,
                max_angle=6.810440,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_NeckTwist02",
        opensim_name="CC_Base_NeckTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-11.946480,
                max_angle=10.421994,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-9.594653,
                max_angle=7.706813,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-9.457112,
                max_angle=8.791300,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Head",
        opensim_name="CC_Base_Head",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-41.868237,
                max_angle=4.219522,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-31.248153,
                max_angle=28.502303,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-14.462350,
                max_angle=12.834244,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_FacialBone",
        opensim_name="CC_Base_FacialBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=89.999982,
                max_angle=90.000030,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000055,
                max_angle=-0.000005,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=90.000071,
                max_angle=90.000125,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_JawRoot",
        opensim_name="CC_Base_JawRoot",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.008309,
                max_angle=-0.008263,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.001287,
                max_angle=0.001326,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=89.997544,
                max_angle=91.929681,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Tongue01",
        opensim_name="CC_Base_Tongue01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000177,
                max_angle=-0.000133,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.019986,
                max_angle=0.020030,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=6.640992,
                max_angle=6.641049,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Tongue02",
        opensim_name="CC_Base_Tongue02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.002996,
                max_angle=-0.002950,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.007889,
                max_angle=-0.007836,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=9.835314,
                max_angle=9.835353,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Tongue03",
        opensim_name="CC_Base_Tongue03",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000219,
                max_angle=-0.000175,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000015,
                max_angle=0.000030,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000332,
                max_angle=0.000371,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Teeth02",
        opensim_name="CC_Base_Teeth02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-179.991290,
                max_angle=-179.991221,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.011389,
                max_angle=-0.011346,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.034029,
                max_angle=0.034079,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Eye",
        opensim_name="CC_Base_R_Eye",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-360.000000,
                max_angle=360.000000,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-97.365296,
                max_angle=-55.841707,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-92.914096,
                max_angle=94.749689,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Eye",
        opensim_name="CC_Base_L_Eye",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-90.001847,
                max_angle=360.000000,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-95.711263,
                max_angle=-62.416331,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-92.923125,
                max_angle=94.755064,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_UpperJaw",
        opensim_name="CC_Base_UpperJaw",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000316,
                max_angle=-0.000274,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.004846,
                max_angle=-0.004807,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=90.000576,
                max_angle=90.000604,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_Teeth01",
        opensim_name="CC_Base_Teeth01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=179.997505,
                max_angle=179.997546,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.003763,
                max_angle=0.003806,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.001948,
                max_angle=-0.001904,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Clavicle",
        opensim_name="CC_Base_L_Clavicle",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-31.536059,
                max_angle=20.165215,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.292865,
                max_angle=13.816843,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-107.416678,
                max_angle=-7.242663,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Upperarm",
        opensim_name="CC_Base_L_Upperarm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-14.856300,
                max_angle=111.419646,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-69.453434,
                max_angle=67.865914,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-114.045444,
                max_angle=4.263985,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Forearm",
        opensim_name="CC_Base_L_Forearm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=0.559156,
                max_angle=113.468492,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-75.258193,
                max_angle=55.856225,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-82.214734,
                max_angle=85.186734,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ForearmTwist01",
        opensim_name="CC_Base_L_ForearmTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000050,
                max_angle=0.000003,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-41.900523,
                max_angle=41.811249,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000686,
                max_angle=-0.000637,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ForearmTwist02",
        opensim_name="CC_Base_L_ForearmTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000496,
                max_angle=0.000713,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-43.362778,
                max_angle=38.878799,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000146,
                max_angle=0.001048,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_ElbowShareBone",
        opensim_name="CC_Base_L_ElbowShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-67.893638,
                max_angle=-1.420383,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-83.172013,
                max_angle=82.493604,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-49.529708,
                max_angle=21.599802,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Hand",
        opensim_name="CC_Base_L_Hand",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-27.690345,
                max_angle=23.942198,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-25.663626,
                max_angle=11.496269,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-43.969790,
                max_angle=54.841925,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky1",
        opensim_name="CC_Base_L_Pinky1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-8.940148,
                max_angle=5.603056,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-8.139346,
                max_angle=8.541609,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-104.942804,
                max_angle=-4.149059,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky2",
        opensim_name="CC_Base_L_Pinky2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.112113,
                max_angle=3.131392,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=0.086302,
                max_angle=1.652846,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-83.547400,
                max_angle=-1.104479,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Pinky3",
        opensim_name="CC_Base_L_Pinky3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.237564,
                max_angle=0.802701,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.312620,
                max_angle=0.377234,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-49.229398,
                max_angle=9.726841,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring1",
        opensim_name="CC_Base_L_Ring1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-1.405099,
                max_angle=5.609528,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-4.996723,
                max_angle=4.903310,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-92.762554,
                max_angle=-2.617411,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring2",
        opensim_name="CC_Base_L_Ring2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.325652,
                max_angle=1.480778,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.006497,
                max_angle=0.028297,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-114.043655,
                max_angle=-5.257178,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Ring3",
        opensim_name="CC_Base_L_Ring3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.846534,
                max_angle=2.370528,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.169863,
                max_angle=0.082655,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-49.497694,
                max_angle=5.105856,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid1",
        opensim_name="CC_Base_L_Mid1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.935568,
                max_angle=6.684497,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.252513,
                max_angle=2.261451,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-85.491436,
                max_angle=-4.200897,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid2",
        opensim_name="CC_Base_L_Mid2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-0.446485,
                max_angle=0.668841,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.026012,
                max_angle=0.161844,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-89.155053,
                max_angle=-0.348354,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Mid3",
        opensim_name="CC_Base_L_Mid3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=2.905389,
                max_angle=3.359008,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.038996,
                max_angle=0.499069,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-53.041152,
                max_angle=5.394840,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index1",
        opensim_name="CC_Base_L_Index1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.020406,
                max_angle=13.080151,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.757308,
                max_angle=11.133388,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-68.875928,
                max_angle=11.868658,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index2",
        opensim_name="CC_Base_L_Index2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.186831,
                max_angle=0.341535,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.137396,
                max_angle=-0.014232,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-71.435781,
                max_angle=-0.014700,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Index3",
        opensim_name="CC_Base_L_Index3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.406275,
                max_angle=2.010651,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.210621,
                max_angle=1.011253,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-62.772048,
                max_angle=10.198092,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb1",
        opensim_name="CC_Base_L_Thumb1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=31.278998,
                max_angle=62.245447,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-15.324774,
                max_angle=41.544492,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-55.592563,
                max_angle=-10.620200,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb2",
        opensim_name="CC_Base_L_Thumb2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-30.562778,
                max_angle=-16.571950,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.073548,
                max_angle=1.170112,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.345488,
                max_angle=2.423290,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Thumb3",
        opensim_name="CC_Base_L_Thumb3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.729012,
                max_angle=38.776835,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.845312,
                max_angle=1.108957,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.507646,
                max_angle=2.536636,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_UpperarmTwist01",
        opensim_name="CC_Base_L_UpperarmTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000309,
                max_angle=0.000552,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-30.142861,
                max_angle=52.932054,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000142,
                max_angle=0.000527,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_UpperarmTwist02",
        opensim_name="CC_Base_L_UpperarmTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000122,
                max_angle=0.000244,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-52.932033,
                max_angle=30.142841,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000187,
                max_angle=0.000113,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_RibsTwist",
        opensim_name="CC_Base_L_RibsTwist",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=78.958264,
                max_angle=78.958353,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.005679,
                max_angle=-0.005639,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=179.968832,
                max_angle=179.968859,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_L_Breast",
        opensim_name="CC_Base_L_Breast",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000020,
                max_angle=0.000025,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.000269,
                max_angle=0.000270,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000032,
                max_angle=0.000010,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_RibsTwist",
        opensim_name="CC_Base_R_RibsTwist",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=78.958216,
                max_angle=78.958326,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.004586,
                max_angle=-0.004540,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=179.969406,
                max_angle=179.969419,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Breast",
        opensim_name="CC_Base_R_Breast",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000033,
                max_angle=0.000014,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.000405,
                max_angle=0.000408,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000029,
                max_angle=0.000011,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Clavicle",
        opensim_name="CC_Base_R_Clavicle",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.759806,
                max_angle=14.889780,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-13.774195,
                max_angle=-1.536163,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=5.976174,
                max_angle=102.700541,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Upperarm",
        opensim_name="CC_Base_R_Upperarm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-70.318867,
                max_angle=108.629193,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-62.138145,
                max_angle=129.077707,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-69.706506,
                max_angle=110.233106,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Forearm",
        opensim_name="CC_Base_R_Forearm",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.259835,
                max_angle=117.794467,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-45.063338,
                max_angle=65.192277,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-65.244132,
                max_angle=123.277319,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ElbowShareBone",
        opensim_name="CC_Base_R_ElbowShareBone",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-107.484173,
                max_angle=60.313057,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-123.420712,
                max_angle=63.420233,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-117.910963,
                max_angle=48.976093,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ForearmTwist01",
        opensim_name="CC_Base_R_ForearmTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000060,
                max_angle=0.000002,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-62.464962,
                max_angle=31.944491,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=0.000649,
                max_angle=0.000733,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_ForearmTwist02",
        opensim_name="CC_Base_R_ForearmTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000497,
                max_angle=0.000757,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-46.900010,
                max_angle=41.026269,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.001239,
                max_angle=-0.000238,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Hand",
        opensim_name="CC_Base_R_Hand",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-34.307518,
                max_angle=46.181238,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-62.121602,
                max_angle=26.182794,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-77.524109,
                max_angle=44.686226,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring1",
        opensim_name="CC_Base_R_Ring1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-0.234201,
                max_angle=8.025249,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-4.901628,
                max_angle=8.642693,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=2.613781,
                max_angle=92.766946,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring2",
        opensim_name="CC_Base_R_Ring2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.308559,
                max_angle=1.469489,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.025975,
                max_angle=-0.004951,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=5.261538,
                max_angle=121.951375,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Ring3",
        opensim_name="CC_Base_R_Ring3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.848793,
                max_angle=2.371376,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-0.119974,
                max_angle=1.167677,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-6.525223,
                max_angle=49.494761,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid1",
        opensim_name="CC_Base_R_Mid1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.412942,
                max_angle=11.189832,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-2.510980,
                max_angle=2.926147,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=4.198335,
                max_angle=79.406051,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid2",
        opensim_name="CC_Base_R_Mid2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.010383,
                max_angle=0.671984,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.216450,
                max_angle=0.007151,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.496869,
                max_angle=112.779523,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Mid3",
        opensim_name="CC_Base_R_Mid3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=2.973802,
                max_angle=3.370994,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.497162,
                max_angle=-0.031590,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-6.377009,
                max_angle=53.040374,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb1",
        opensim_name="CC_Base_R_Thumb1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=29.338354,
                max_angle=55.740170,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-49.322773,
                max_angle=15.340395,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=10.618596,
                max_angle=53.628084,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb2",
        opensim_name="CC_Base_R_Thumb2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-32.078895,
                max_angle=-17.600119,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.288115,
                max_angle=0.067858,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-2.432038,
                max_angle=-1.465050,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Thumb3",
        opensim_name="CC_Base_R_Thumb3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-37.722800,
                max_angle=38.716446,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.110323,
                max_angle=0.923005,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-2.535775,
                max_angle=-1.483409,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index1",
        opensim_name="CC_Base_R_Index1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=2.024689,
                max_angle=13.280942,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-11.130931,
                max_angle=1.759482,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-11.852376,
                max_angle=59.336879,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index2",
        opensim_name="CC_Base_R_Index2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.171866,
                max_angle=0.341723,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=0.014718,
                max_angle=0.140386,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=0.018494,
                max_angle=79.249578,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Index3",
        opensim_name="CC_Base_R_Index3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=1.359972,
                max_angle=2.037597,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.009636,
                max_angle=0.212728,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-10.105561,
                max_angle=62.769807,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky1",
        opensim_name="CC_Base_R_Pinky1",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=-7.811516,
                max_angle=5.614181,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-8.533954,
                max_angle=12.710864,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=4.148347,
                max_angle=109.743368,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky2",
        opensim_name="CC_Base_R_Pinky2",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=False,
                min_angle=1.352103,
                max_angle=3.106842,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-1.669014,
                max_angle=-0.086847,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=1.112503,
                max_angle=100.627285,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_Pinky3",
        opensim_name="CC_Base_R_Pinky3",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=-0.011448,
                max_angle=0.805677,
            ),
            y_axis=AxisConstraint(
                locked=True,
                min_angle=-0.376485,
                max_angle=0.312126,
            ),
            z_axis=AxisConstraint(
                locked=False,
                min_angle=-9.736617,
                max_angle=49.219501,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_UpperarmTwist01",
        opensim_name="CC_Base_R_UpperarmTwist01",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000321,
                max_angle=0.000555,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-51.912470,
                max_angle=30.353931,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000458,
                max_angle=0.000191,
            ),
        ),
        export_body=True
    ))

    config.add_bone(BoneConfig(
        blender_name="CC_Base_R_UpperarmTwist02",
        opensim_name="CC_Base_R_UpperarmTwist02",
        constraints=JointConstraints(
            joint_type=JointType.CUSTOM,
            x_axis=AxisConstraint(
                locked=True,
                min_angle=0.000129,
                max_angle=0.000242,
            ),
            y_axis=AxisConstraint(
                locked=False,
                min_angle=-30.353945,
                max_angle=51.912446,
            ),
            z_axis=AxisConstraint(
                locked=True,
                min_angle=-0.000154,
                max_angle=0.000136,
            ),
        ),
        export_body=True
    ))

    return config
